CDECK  ID>, STEVENSON.
      DOUBLE PRECISION  FUNCTION STEVENSON(AA,IZERO)
      IMPLICIT REAL*8(A-H,L-Z)
      COMMON/OPTIMGUI/AB,AC,ALQ2S
      STEVENSON=ALQ2S-2.D0*(1.D0/AA+AC*
     1      DLOG(.5D0*AA*AB/(1.D0+AA*AC)))/AB
      RETURN
      END
